package main

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/gammazero/nexus/v3/wamp"
	"gopkg.in/yaml.v3"
)

type Mapping interface {
	MatchClusterToInstance(instance string, cluster string) bool
	MatchInstance(uri wamp.URI) (string, bool)
	MatchCluster(uri wamp.URI) (string, bool)
}

type MappingNone struct{}

func (MappingNone) MatchInstance(uri wamp.URI) (string, bool) {
	return fourthUriSegment(uri)
}
func (MappingNone) MatchCluster(uri wamp.URI) (string, bool) {
	return fourthUriSegment(uri)
}
func (MappingNone) MatchClusterToInstance(instance string, cluster string) bool {
	return false
}

// instance id should have a prefix; cluster id should have a prefix;
// clusters and instances are mapped onto each other 1:1
type MappingIso struct {
	PrefixInstance string `json:"prefix-instance" yaml:"prefix-instance"`
	PrefixCluster  string `json:"prefix-cluster" yaml:"prefix-cluster"`
}

func (m MappingIso) MatchInstance(uri wamp.URI) (string, bool) {
	n, ok := fourthUriSegment(uri)
	if !ok {
		return "", false
	}
	return strings.CutPrefix(n, m.PrefixInstance)
}
func (m MappingIso) MatchCluster(uri wamp.URI) (string, bool) {
	n, ok := fourthUriSegment(uri)
	if !ok {
		return "", false
	}
	return strings.CutPrefix(n, m.PrefixCluster)
}
func (m MappingIso) MatchClusterToInstance(instance string, cluster string) bool {
	return instance == cluster
}

type MappingStatic struct {
	ClusterToInstance map[string]string `json:"cluster-to-instance" yaml:"cluster-to-instance"`
}

func (m MappingStatic) MatchInstance(uri wamp.URI) (string, bool) {
	n, ok := fourthUriSegment(uri)
	if !ok {
		return "", false
	}
	for _, v := range m.ClusterToInstance {
		if v == n {
			return n, true
		}
	}
	return "", false
}

func (m MappingStatic) MatchCluster(uri wamp.URI) (string, bool) {
	n, ok := fourthUriSegment(uri)
	if !ok {
		return "", false
	}
	for k := range m.ClusterToInstance {
		if k == n {
			return n, true
		}
	}
	return "", false
}
func (m MappingStatic) MatchClusterToInstance(instance string, cluster string) bool {
	foundInstance, ok := m.ClusterToInstance[cluster]
	return ok && foundInstance == instance
}

func fourthUriSegment(uri wamp.URI) (string, bool) {
	if !strings.HasPrefix(string(uri), "com.viinex.api.") {
		return "", false
	}
	parts := strings.Split(string(uri), ".")
	if len(parts) == 4 {
		return parts[3], true
	} else {
		return "", false
	}
}

// JSON deserialization code was generated by Gemini

// PolymorphicMapping is a wrapper to enable polymorphic deserialization of the Mapping interface.
// By embedding the Mapping interface, it satisfies the interface itself.
type PolymorphicMapping struct {
	Mapping
}

// UnmarshalJSON provides the custom deserialization logic.
func (pm *PolymorphicMapping) UnmarshalJSON(data []byte) error {
	// Temporary struct to determine the mapping type.
	var typeDetector struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &typeDetector); err != nil {
		// If there's no type, we can default to 'none'.
		// This handles cases where the mapping object is empty or not specified.
		if _, ok := err.(*json.UnmarshalTypeError); ok || string(data) == "null" || string(data) == "{}" {
			pm.Mapping = &MappingNone{}
			return nil
		}
		return fmt.Errorf("error detecting mapping type: %w", err)
	}

	switch typeDetector.Type {
	case "none", "": // Also handle empty type string
		pm.Mapping = &MappingNone{}
		return nil
	case "iso":
		var m MappingIso
		if err := json.Unmarshal(data, &m); err != nil {
			return fmt.Errorf("error unmarshaling to MappingIso: %w", err)
		}
		pm.Mapping = &m
		return nil
	case "static":
		var m MappingStatic
		if err := json.Unmarshal(data, &m); err != nil {
			return fmt.Errorf("error unmarshaling to MappingStatic: %w", err)
		}
		pm.Mapping = &m
		return nil
	}

	return fmt.Errorf("unknown mapping type: %s", typeDetector.Type)
}

func (pm *PolymorphicMapping) UnmarshalYAML(node *yaml.Node) error {
	var typeDetector struct {
		Type string `yaml:"type"`
	}
	if err := node.Decode(&typeDetector); err != nil {
		// Handle cases where the node is empty or doesn't have a type field.
		pm.Mapping = &MappingNone{}
		return nil
	}

	switch typeDetector.Type {
	case "none", "":
		pm.Mapping = &MappingNone{}
		return nil
	case "iso":
		var m MappingIso
		if err := node.Decode(&m); err != nil {
			return fmt.Errorf("error unmarshaling to MappingIso from YAML: %w", err)
		}
		pm.Mapping = &m
		return nil
	case "static":
		var m MappingStatic
		if err := node.Decode(&m); err != nil {
			return fmt.Errorf("error unmarshaling to MappingStatic from YAML: %w", err)
		}
		pm.Mapping = &m
		return nil
	}

	return fmt.Errorf("unknown mapping type: '%s'", typeDetector.Type)
}
